<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSSfqa5a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSSfqa5a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSSfqa5a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSSfqa5a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSSfqa5a\App_KernelDevDebugContainer([
    'container.build_hash' => 'SSfqa5a',
    'container.build_id' => 'b110ee4b',
    'container.build_time' => 1766388051,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSSfqa5a');
