<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_order_create' => [[], ['_controller' => 'App\\Controller\\OrderController::create'], [], [['text', '/orders']], [], [], []],
    'app_order_detail' => [['id'], ['_controller' => 'App\\Controller\\OrderController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/orders']], [], [], []],
    'app_order_checkout' => [['id'], ['_controller' => 'App\\Controller\\OrderController::checkout'], [], [['text', '/checkout'], ['variable', '/', '[^/]++', 'id', true], ['text', '/orders']], [], [], []],
    'app_product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::list'], [], [['text', '/products']], [], [], []],
    'app_product_create' => [[], ['_controller' => 'App\\Controller\\ProductController::create'], [], [['text', '/products']], [], [], []],
    'App\Controller\OrderController::create' => [[], ['_controller' => 'App\\Controller\\OrderController::create'], [], [['text', '/orders']], [], [], []],
    'App\Controller\OrderController::detail' => [['id'], ['_controller' => 'App\\Controller\\OrderController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/orders']], [], [], []],
    'App\Controller\OrderController::checkout' => [['id'], ['_controller' => 'App\\Controller\\OrderController::checkout'], [], [['text', '/checkout'], ['variable', '/', '[^/]++', 'id', true], ['text', '/orders']], [], [], []],
    'App\Controller\ProductController::list' => [[], ['_controller' => 'App\\Controller\\ProductController::list'], [], [['text', '/products']], [], [], []],
    'App\Controller\ProductController::create' => [[], ['_controller' => 'App\\Controller\\ProductController::create'], [], [['text', '/products']], [], [], []],
];
