<?php

namespace ContainerSSfqa5a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeedCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SeedCommand' shared autowired service.
     *
     * @return \App\Command\SeedCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SeedCommand.php';

        $container->privates['App\\Command\\SeedCommand'] = $instance = new \App\Command\SeedCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:seed');

        return $instance;
    }
}
